version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    rebase-strategy: auto
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    rebase-strategy: auto
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    rebase-strategy: auto
    schedule:
      interval: daily
