version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    rebase-strategy: auto
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: docker
    directory: /
    rebase-strategy: auto
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: github-actions
    directory: /
    rebase-strategy: auto
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: npm
    directory: /docs
    rebase-strategy: auto
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
