version: '2'

linters:
  settings:
    lll:
      line-length: 80
      tab-width: 4
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - lll

formatters:
  enable:
    - gofumpt
    - golines
    - gci
  settings:
    golines:
      max-len: 80
      tab-len: 4
      shorten-comments: true
      reformat-tags: false
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/loderunner/scrt)
