run:
  skip-dirs-use-default: false

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - errchkjson
    - errorlint
    - godot
    - gofmt
    - goimports
    - misspell
    - prealloc
    - revive
    - unconvert
    - whitespace

issues:
  include:
    - EXC0002
