builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - replacements:
      '386': i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
nfpms:
  - id: linux_packages
    replacements:
      '386': i386
      amd64: x86_64
    homepage: https://scrt.run
    maintainer: Charles Francoise <scrt@scrt.run>
    description: A secret manager for the command-line
    license: Apache 2.0
    formats:
      - deb
      - rpm
    section: devel
    rpm:
      signature:
        key_file: key.gpg
    deb:
      signature:
        key_file: key.gpg
brews:
  - goarm: '6'
    tap:
      owner: loderunner
      name: homebrew-scrt
    commit_author:
      name: Charles Francoise
      email: scrt@scrt.run
    homepage: 'https://scrt.run'
    description: 'A secret manager for the command-line'
    license: 'Apache-2.0'
    install: bin.install "scrt"
    test: system "#{bin}/scrt --version"
    skip_upload: auto
dockers:
  # Tag release
  - image_templates:
      - 'loderunner/scrt:{{ .Major }}'
      - 'loderunner/scrt:{{ .Major }}.{{ .Minor }}'
      - 'loderunner/scrt:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
      - 'loderunner/scrt:latest'
    skip_push: auto
  # Prerelease
  - image_templates:
      - 'loderunner/scrt:{{ .Version }}'
checksum:
  name_template: 'checksums.txt'
  ids:
    - default
snapshot:
  name_template: '{{ .RawVersion }}-dev-{{ .ShortCommit }}'
release:
  ids:
    - default
