before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - replacements:
      386: i386
      amd64: x86_64
nfpms:
  - replacements:
      386: i386
      amd64: x86_64
    homepage: https://github.com/loderunner/scrt
    maintainer: Charles Francoise <charles.francoise@gmail.com>
    description: A secret manager for the command-line
    license: Apache 2.0
    formats:
      - deb
      - rpm
    section: devel
    rpm:
      signature:
        key_file: key.gpg
    deb:
      signature:
        key_file: key.gpg
brews:
  - goarm: 6
    tap:
      owner: loderunner
      name: homebrew-tap
    commit_author:
      name: Charles Francoise
      email: charles.francoise@gmail.com
    homepage: "https://github.com/loderunner/scrt"
    description: "A secret manager for the command-line"
    license: "Apache-2.0"
    install: bin.install "scrt"
    test: system "#{bin}/scrt --version"
dockers:
  - image_templates:
      - "loderunner/scrt:{{ .Major }}"
      - "loderunner/scrt:{{ .Major }}.{{ .Minor }}"
      - "loderunner/scrt:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "loderunner/scrt:latest"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .RawVersion }}-dev-{{ .ShortCommit }}"
