builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - id: linux_packages
    replacements:
      386: i386
      amd64: x86_64
    homepage: https://github.com/loderunner/scrt
    maintainer: Charles Francoise <scrt@scrt.run>
    description: A secret manager for the command-line
    license: Apache 2.0
    formats:
      - deb
      - rpm
    section: devel
    rpm:
      signature:
        key_file: key.gpg
    deb:
      signature:
        key_file: key.gpg
brews:
  - goarm: 6
    tap:
      owner: loderunner
      name: homebrew-scrt
    commit_author:
      name: Charles Francoise
      email: scrt@scrt.run
    homepage: "https://github.com/loderunner/scrt"
    description: "A secret manager for the command-line"
    license: "Apache-2.0"
    install: bin.install "scrt"
    test: system "#{bin}/scrt --version"
    skip_upload: auto
dockers:
  # Tag release
  - image_templates:
      - "loderunner/scrt:{{ .Major }}"
      - "loderunner/scrt:{{ .Major }}.{{ .Minor }}"
      - "loderunner/scrt:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "loderunner/scrt:latest"
    skip_push: auto
  # Prerelease
  - image_templates:
      - "loderunner/scrt:{{ .Version }}"
checksum:
  name_template: "checksums.txt"
  ids:
    - default
snapshot:
  name_template: "{{ .RawVersion }}-dev-{{ .ShortCommit }}"
release:
  ids:
    - default
publishers:
  - name: apt
    ids:
      - linux_packages
    cmd: .scripts/publish_apt
    env:
      - "KEY_FILE=key.gpg"
      - "PASSPHRASE={{ .Env.NFPM_LINUX_PACKAGES_PASSPHRASE }}"
      - "GITHUB_TOKEN={{ .Env.GITHUB_TOKEN }}"
      - "APT_REPOSITORY=loderunner/scrt-apt"
      - "DEST_DIR={{ .Env.HOME }}/scrt-apt"
      - "SIG_EMAIL=scrt@scrt.run"
      - "VERSION={{ .Version }}"
      - "GIT_AUTHOR_NAME='Charles Francoise'"
      - "GIT_AUTHOR_EMAIL=scrt@scrt.run"
      - "GIT_COMMITTER_NAME='Charles Francoise'"
      - "GIT_COMMITTER_EMAIL=scrt@scrt.run"
  - name: yum
    ids:
      - linux_packages
    cmd: .scripts/publish_yum
    env:
      - "KEY_FILE=key.gpg"
      - "PASSPHRASE={{ .Env.NFPM_LINUX_PACKAGES_PASSPHRASE }}"
      - "GITHUB_TOKEN={{ .Env.GITHUB_TOKEN }}"
      - "YUM_REPOSITORY=loderunner/scrt-yum"
      - "DEST_DIR={{ .Env.HOME }}/scrt-yum"
      - "SIG_EMAIL=scrt@scrt.run"
      - "VERSION={{ .Version }}"
      - "GIT_AUTHOR_NAME='Charles Francoise'"
      - "GIT_AUTHOR_EMAIL=scrt@scrt.run"
      - "GIT_COMMITTER_NAME='Charles Francoise'"
      - "GIT_COMMITTER_EMAIL=scrt@scrt.run"
