name: Publish scrt

on:
  push:
    tags:
      - 'test/*'

jobs:
  test-release-notes:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo truncated ref name
        run: echo "${GITHUB_REF_NAME:6}"
      - name: Echo sed script
        run: echo "/^## ${GITHUB_REF_NAME:6}/,/^##[^#]/p"
      - name: Create release notes
        run: sed -n "/^## ${GITHUB_REF_NAME:6}/,/^##[^#]/p" CHANGELOG.md | sed '$d'
